cuitter/config/routes.rb
Rails.application.routes.draw do
  # ------------------
  # Sessions 
  # ------------------
  get     'sign_up' => 'sessions#sign_up',      :as => 'sign_up'
  post    'connect' => 'sessions#create',   :as => 'connect'
  get     'log_in'  => 'sessions#log_in',      :as => 'log_in'
  delete  'log_out' => 'sessions#destroy',  :as => 'log_out'

  # ------------------
  # Welcome
  # ------------------
  get     'welcome/index'

  # ------------------
  # Resources
  # ------------------
  resources :users do
    resources :posts
  end

  # > Likes ressources
  resources :likes, only: [:create, :destroy]

  # ------------------
  # Root
  # ------------------
  root    'welcome#index' #temp
end

cuitter/app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    # -----------------------------
    # Validates
    # -----------------------------

    # > User
    validates :user, presence: true

    # > Content
    validates :content, length: {minimum: 1, maximum: 150}, presence: true

    # > Origin post
    # validates :origin_post, allow_nil: true #> You need to supply at least one validation
end

cuitter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # -----------------------------
  # New
  # -----------------------------
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  # -----------------------------
  # Create
  # -----------------------------
  def create
    @user = User.find(session[:current_user_id])

    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_path(@user)
    else
      render 'users/edit'
    end
  end

  # -----------------------------
  # Edit
  # -----------------------------
  def edit
    @user = User.find(session[:current_user_id])
    @post = Post.find(params[:id])
  end

  # -----------------------------
  # Update
  # -----------------------------
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to user_path(session[:current_user_id])
    else
      render 'edit'
    end
  end

  # -----------------------------
  # Show
  # -----------------------------
  def show
    @post = Post.find(params[:id])
  end

  # -----------------------------
  # Index
  # -----------------------------
  def index
  end

  # -----------------------------
  # Destroy
  # -----------------------------
  def destroy
    # render plain: params.inspect
    @post = Post.find(params[:id])
    @post.delete

    redirect_to user_path(params[:user_id])
  end

private
  def post_params
    params.require(:post).permit(:content)
  end
end

cuitter/app/helpers/posts_helper.rb
module PostsHelper
end

cuitter/app/views/posts/_new_form.html.erb
<!-- Post something form -->
<%= form_with model: @post, :url => user_posts_path(@user) do |form|  %>
    <!-- Error management -->
    <%= render 'show_post_errors', locals: {:_post => @post} %>
    
    <!-- content -->
    <%= form.label :content, 'What\'s on your mind ?' %></br>
    <%= form.text_area :content %></br>

    <!-- Submit -->
    <%= form.submit 'Post !'%>

<% end %>

    

cuitter/app/views/posts/_show.html.erb
<% 
    # -----------------------------
    # Add the mentions in the post content
    # -----------------------------
    def addMentionLinks(text)
        # @mention management
        newText = text.dup
        text.scan(/@(\w+)/) do |mentions|
            mentions.each do |mentionnedUser|
                atMention = "@#{mentionnedUser}"
                user = User.find_by( nickname: mentionnedUser )
                if user.nil? == false
                    newText.gsub!(atMention, (link_to atMention, user_path(user))) 
                end
            end
        end

        # return
        newText
    end

    # -----------------------------
    # Add the custom links in the post content
    # -----------------------------
    def addUrlLinks(text)
        # @mention management
        newText = text.dup
        text.scan(/((?:http|www)[^\s]+\.\w+)/) do |links|
            links.each do |link|
                externLink = link.dup;
                externLink = "http://#{link}" if link.include?('http://') == false
                newText.gsub!(link, (link_to nil, externLink)) 
            end
        end

        # return
        newText
    end

    # -----------------------------
    # Add the all the links in the post content
    # -----------------------------
    def addLinksToPost(post)
        resultText = post.content
        resultText = addMentionLinks(resultText)
        addUrlLinks(resultText)

    end
%>



<p>
    <%= _post.created_at %>
    <% if _post.updated_at != _post.created_at %>
        (Edited)
    <% end %>
    
    <% if _post.user.id == session[:current_user_id] %>
        <%= link_to 'Edit', edit_user_post_url(@user, _post) %>
        <%= link_to 'Show', user_post_url(@user, _post) %>
        <%= link_to 'Delete', user_post_url(@user, _post), method: :delete %>
    <% end %>
    
    </br>

    <% concat addLinksToPost(_post).html_safe %></br>
    
    <% if @likes[@user.id] %>
        You like this !
    <% else %>
        <%= button_to 'Like', {:controller => 'likes', :action => 'create', :user_id => @user.id, :post_id => _post.id} %></br></br>
    <% end %>

</p>

cuitter/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

cuitter/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

cuitter/app/views/posts/edit.html.erb
<!-- Post something form -->
<%= form_with model: @post, local: true, :url => user_post_path(@user, @post) do |form|  %>
    <!-- Error management -->
    <%= render 'show_post_errors', locals: {:_post => @post} %>
    
    <!-- content -->
    <%= form.label :content %></br>
    <%= form.text_area :content %></br>

    <!-- Submit -->
    <%= form.submit 'Edit !'%>

<% end %>

    

cuitter/app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

cuitter/app/views/posts/new.html.erb
<%= render 'new_form' %>

cuitter/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

cuitter/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>