cuitter/config/routes.rb
Rails.application.routes.draw do
  # ------------------
  # Sessions 
  # ------------------
  get     'sign_up' => 'sessions#sign_up',      :as => 'sign_up'
  post    'connect' => 'sessions#create',   :as => 'connect'
  get     'log_in'  => 'sessions#log_in',      :as => 'log_in'
  delete  'log_out' => 'sessions#destroy',  :as => 'log_out'

  # ------------------
  # Welcome
  # ------------------
  get     'welcome/index'

  # ------------------
  # Resources
  # ------------------
  resources :users do
    resources :posts
  end

  # > Likes ressources
  resources :likes, only: [:create, :destroy]

  # ------------------
  # Root
  # ------------------
  root    'welcome#index' #temp
end

cuitter/app/models/user.rb
class User < ApplicationRecord
    has_many :posts


# -----------------------------
# Validates
# -----------------------------

# > Nickname
validates :nickname, length: {minimum: 1, maximum: 25}, presence: true,
            uniqueness: {message: -> (object, data) do "#{data[:value]} is already taken." end}

# > Bio
validates :bio, length: {maximum: 75}, allow_blank: true

# > Email
validates :email, allow_blank: false, presence: true,
            uniqueness: {message: -> (object, data) do "#{data[:value]} is already used." end}

# > Password
validates :password, presence: true, length: {minimum: 5}, on: :create

# -----------------------------
# Validates - Format
# -----------------------------

# > Nickname
validates_format_of :nickname, with: /[A-Za-z]/, on: :create, message: "is invalid (format)"

# > Email
validates_format_of :email, with: /\A\w+@\w+\.\w+\z/, on: :create, message: "is invalid (format)"
end

cuitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
    include BCrypt


    # -----------------------------
    # New
    # -----------------------------
    def new 
    end

    # -----------------------------
    # Create
    # -----------------------------
    def create 
        params = user_params_create
        @user = User.new(params.except(:password_double_check))
        
        if params[:password] == params[:password_double_check]
            
            sha1_password = Digest::SHA1.hexdigest("#{params[:password]}")
            @user.password = BCrypt::Password.create(sha1_password).to_s

            if @user.save 
                redirect_to log_in
            else
                render 'sessions/sign_up'
            end
        else
            @user.errors.add(:password, ': The two passwords don\'t match')
            render 'sessions/sign_up'
        end
    end

    # -----------------------------
    # Show
    # -----------------------------
    def show 
        @user = User.find(params[:id])
        @post = Post.new
        @posts = Post.where(:user => params[:id]).order( created_at: :desc )
        @likes = {}
        @posts.each do |post|
            @likesRequest = Like.find_by(post_id: post.id)
            @likes.merge(post.id => @likesRequest) unless @likesRequest.nil?
        end
    end

    # -----------------------------
    #  Index
    # -----------------------------
    def index 
        @users = User.all #todo: user search page
    end

    
    # -----------------------------
    #  Log in
    # -----------------------------
    def log_in
        @user = User.new
    end

    # -----------------------------
    # Edit
    # -----------------------------
    def edit
        @user = User.find(params[:id])
    end

    # -----------------------------
    # Update
    # -----------------------------
    def update 
        @user = User.find(params[:id])
        if @user.update(bio: params[:user][:bio], birthday: params[:user][:birthday])
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    # -----------------------------
    #  Destroy
    # -----------------------------
    def destroy 
        @user = User.find(params[:id])
        @user.destroy 
        redirect_to users_path
    end


private
    # -----------------------------
    # User params - Create
    # -----------------------------
    def user_params_create
        params.require(:user).permit(:nickname, :email, :birthday, :password, :password_double_check)
    end
end

cuitter/app/helpers/users_helper.rb
module UsersHelper
end

cuitter/app/views/users/_show_detailed.html.erb
<% if _user.nil? == false %>

<!-- Nickame -->
<%= _user.nickname %> </br>

<!-- Email -->
<p> 
    Email: 
    <%= _user.email %> 
</p>

<!-- Bio  -->
<p> Bio: </p> </br>
<%= _user.bio %>

<% end %>

cuitter/app/views/users/_show_short.html.erb
<% if _user.nil? == false %>

<!-- Nickame -->
<%= link_to "#{_user.nickname}", user_path(_user) %> </br>

<% end %>

cuitter/app/views/users/_show_timeline.html.erb
<% if defined?(_posts) %>
    <% _posts.each do |post| %>
        <%= render partial: 'posts/show', locals: {:_post => post} %>
    <% end %>

<% end %>

cuitter/app/views/users/edit.html.erb
<%= render partial: 'show_users_errors', locals: {:_user => @user} %>

<%= form_with model: @user, local: true do |form| %>

    <!-- Bio -->
    <%= form.label :bio %></br>
    <%= form.text_area :bio %></br>

    <!-- Birthday -->
    <%= form.label :birthday %>
    <%= form.date_field :birthday %></br>

    <!-- Submit -->
    <%= form.submit 'Update' %>

<% end %>

cuitter/app/views/users/index.html.erb
<% if @users.nil? == false && @users.empty? == false %>
    <p> List of all users: </p> </br>
    <!-- Render all users -->
    <!-- TODO: user search -->
    <% @users.each do |user| %>
        <%= render partial: 'show_short', locals: {:_user => user} %>
    <% end %>

<% end %>

cuitter/app/views/users/new.html.erb
<%= params.inspect %>

cuitter/app/views/users/show.html.erb
<!-- Edit button for user profile -->
<% if defined?(session) && @user.id == session[:current_user_id] %>
    <%= link_to 'Edit', edit_user_path(@user) %> </br>
<% end%>

<!-- Name + bio -->
<h1> <%= @user.nickname %> </h1>
<div> <%= @user.bio %> </div>

<!-- Post something form if current profile -->
<% if defined?(session) && @user.id == session[:current_user_id] %>
    <%= render partial: 'posts/new_form', locals: {:_user => @user, :_post => @post} %>
<% end %>



<!-- Print thread -->
<%= render partial: 'show_timeline', locals: {:_posts => @posts} %>